basePath: /api/v1
info:
  contact:
    email: Jacksontpa7@gmail.com
  license:
    name: MIT
  version: "1.0"
paths:
  /confirm-payment:
    get:
      description: confirms a payment on Hedera
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Confirm a payment
      tags:
      - Payment
swagger: "2.0"
