basePath: /api/v1
definitions:
  dtos.CreateBillItemResponse:
    properties:
      itemId:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  dtos.CreateBillParticipantResponse:
    properties:
      amountOwed:
        type: integer
      isPaid:
        type: boolean
      items:
        items:
          $ref: '#/definitions/dtos.CreateBillItemResponse'
        type: array
      participantId:
        type: string
    type: object
  dtos.CreateBillRequest:
    properties:
      billTitle:
        example: Dinner at Cafe
        type: string
      creatorId:
        example: user123
        type: string
      participants:
        items:
          $ref: '#/definitions/dtos.CreateParticipantRequest'
        type: array
      totalAmount:
        example: 200000
        type: integer
    type: object
  dtos.CreateBillResponse:
    properties:
      billId:
        type: string
      billTitle:
        type: string
      createdAt:
        type: string
      creatorId:
        type: string
      participants:
        items:
          $ref: '#/definitions/dtos.CreateBillParticipantResponse'
        type: array
      totalAmount:
        type: integer
    type: object
  dtos.CreateItemRequest:
    properties:
      name:
        example: Steak
        type: string
      price:
        example: 80000
        type: integer
    type: object
  dtos.CreateParticipantRequest:
    properties:
      amountOwed:
        example: 100000
        type: integer
      isPaid:
        example: true
        type: boolean
      items:
        items:
          $ref: '#/definitions/dtos.CreateItemRequest'
        type: array
      participantId:
        example: user123
        type: string
    type: object
  dtos.GetParticipantDetailRequest:
    properties:
      billId:
        type: string
      participantId:
        type: string
    required:
    - billId
    - participantId
    type: object
  dtos.ParticipantDetailResponse:
    properties:
      billId:
        type: string
      billTitle:
        type: string
      creatorId:
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      participantId:
        type: string
      totalOwed:
        type: integer
    type: object
  models.Item:
    properties:
      billId:
        type: string
      itemId:
        type: string
      name:
        type: string
      participantId:
        type: string
      price:
        type: integer
    type: object
  models.User:
    properties:
      wallet_address:
        type: string
    type: object
info:
  contact:
    email: Jacksontpa7@gmail.com
  license:
    name: MIT
  version: "1.0"
paths:
  /bills/create-bill:
    post:
      consumes:
      - application/json
      description: Create a bill with participants and their items
      parameters:
      - description: Bill Info
        in: body
        name: bill
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateBillRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CreateBillResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new bill
      tags:
      - Bill
  /check:
    get:
      description: Check backend health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Check backend health
      tags:
      - Payment
  /confirm-payment:
    get:
      description: example return confirms a payment on Hedera
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Example confirm a payment
      tags:
      - Payment
  /participants/get-all-participant-detail/{participantId}:
    get:
      consumes:
      - application/json
      description: Get participant all bills
      parameters:
      - description: Participant ID
        in: path
        name: participantId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ParticipantDetailResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get participant Bills
      tags:
      - Participants
  /participants/get-participant-detail:
    post:
      consumes:
      - application/json
      description: Retrieve participant detail including bill and items using billId
        and participantId
      parameters:
      - description: Bill and Participant IDs
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.GetParticipantDetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ParticipantDetailResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get participant detail in a bill
      tags:
      - Participant
  /users/register:
    post:
      consumes:
      - application/json
      description: Save wallet address to database
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - users
swagger: "2.0"
